@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 02 10:03:15 -0700 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim prelab4_behav -key {Behavioral:sim_1:Functional:prelab4} -tclbatch prelab4.tcl -view C:/Users/sdli/Downloads/Lab04FINALFINAL.xpr/Lab04/Lab04.srcs/sim_1/imports/Downloads/Lab04.xpr/Lab04/stateMachineLab4_behav.wcfg -log simulate.log"
call xsim  prelab4_behav -key {Behavioral:sim_1:Functional:prelab4} -tclbatch prelab4.tcl -view C:/Users/sdli/Downloads/Lab04FINALFINAL.xpr/Lab04/Lab04.srcs/sim_1/imports/Downloads/Lab04.xpr/Lab04/stateMachineLab4_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
